export const LEAD_STATUSES = {
  PRE_APPLICATION: [
    "New Inquiry",
    "Contacted",
    "Counselling Scheduled",
    "Counselling Completed",
    "Interested – Not Ready",
    "Eligible to Apply",
    "Not Eligible",
    "Awaiting Documents",
    "Documents Partially Received",
    "Documents Complete – Ready to Apply",
    "Application in Preparation",
    "Lead Closed – Spam",
    "Lead Closed – No Response",
  ],
  SUBMISSION: [
    "Application Submitted to University",
    "Application Submitted – Awaiting Acknowledgment",
    "Acknowledged by University",
    "Application Paid – University Fees",
    "Application Under Initial Review",
    "Application Under Academic Review",
    "Application Under Department Review",
    "Additional Documents Requested",
    "Documents Resubmitted",
    "Awaiting Decision",
  ],
  DECISION: [
    "Offer Issued – Conditional",
    "Offer Issued – Unconditional",
    "Offer Issued – With Interview",
    "Interview Prep Scheduled",
    "Interview Scheduled",
    "Interview Completed",
    "Waitlisted",
    "Deferred to Next Intake",
    "Application Rejected",
    "Application Withdrawn",
    "On Hold – Student Side",
    "On Hold – University Side",
    "On Hold – Unireach Side",
    "Pending – Student Side",
    "Pending – University Side",
    "Pending – Unireach Side",
  ],
  ACCEPTANCE: [
    "Offer Sent to Student",
    "Offer Accepted by Student",
    "Offer Declined by Student",
    "Bank Loan Guidance Provided",
    "Financial Documents Verified",
    "Deposit Invoice Sent",
    "Deposit Paid",
    "Deposit Pending",
    "Confirmation of Enrollment (CoE) Issued",
    "Enrollment Confirmed",
  ],
  VISA: [
    "Visa Documents in Preparation",
    "Visa Submitted",
    "Visa Under Processing",
    "Visa Approved",
    "Visa Refused",
    "Visa Appeal in Progress",
    "Pre-Departure Briefing Scheduled",
    "Pre-Departure Completed",
    "Accommodation Arranged",
    "Flight Booked",
  ],
  POST_ENROLLMENT: [
    "Student Enrolled",
    "Orientation Completed",
    "Arrived in Destination",
    "No Show",
    "Deferred After Visa",
    "Dropped Before Start",
    "Active Student",
    "Completed First Semester",
    "Graduated",
  ],
  INTERNAL: [
    "Escalated to University",
    "Awaiting Partner Feedback",
    "Ready for Compliance Audit",
    "Commission Pending",
    "Commission Received",
    "Case Closed",
  ],
};

export const ALL_LEAD_STATUSES = Object.values(LEAD_STATUSES).flat();

export const DEFAULT_LEAD_STATUS = "New Inquiry";
